### ISSUE TITLE
_ to -

### ISSUE THREAD

**Issue by catrock31** [Ripthulhu/VFIO-SGPU#1]
sudo chmod +x install_hooks.sh sudo ./install_hooks.sh you need to change them to sudo chmod +x install-hooks.sh sudo ./install-hooks.sh

**Comment by royalgraphx** [comment]
he/we are aware, the readme is a placeholder, and this was barely made today.

**Comment by Ripthulhu** [comment]
These aren't the final instructions and indeed more of a placeholder, but I corrected it for now

**Comment by Ripthulhu** [comment]
These aren't the final instructions and indeed more of a placeholder, but I corrected it for now
